[package]
name = "devout"
version = "0.2.0"
license = "Apache-2.0 OR BSL-1.0 OR MIT"
description = "A simple cross-platform logging library"
repository = "https://github.com/AldaronLau/devout"
documentation = "https://docs.rs/devout"
homepage = "https://github.com/AldaronLau/devout/releases"
include = [
    "/LICENSE_APACHE",
    "/LICENSE_BOOST",
    "/LICENSE_MIT",
    "/README.md",
    "/src/*",
]
categories = ["development-tools::debugging", "wasm"]
keywords = ["logging", "print", "wasm", "journal", "output"]
readme = "README.md"
edition = "2018"

# Use web-sys and wasm-bingen to log to wasm console
[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3"
features = ["console"]
[target.'cfg(target_arch = "wasm32")'.dependencies.wasm-bindgen]
version = "0.2"
